name: doctor_appointment
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.2
  http: ^1.3.0
  intl: ^0.20.2
  geolocator: ^13.0.2
  permission_handler: ^11.4.0
  url_launcher: ^6.3.1
  flutter_local_notifications: ^18.0.1
  table_calendar: ^3.2.0
  map_launcher: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
